language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - extra-google-google_play_services
  licenses:
    - '.+'
script:
    - ./gradlew assembleConversationsFreeSystemRelease
    - ./gradlew assembleQuicksyFreeCompatRelease
    - sonar-scanner
addons:
  sonarcloud:
    organization: "maikokuipers-bitbucket"
    token:
      secure: "RXarAW9H6e95srR9geNa7f1b1Ga5L03/37mgNF3t3ejTO/luZ3cEQUX/5reJyxriUBSanEobiJzUg6eJ4vMoxL37Hv6M9lqh+55PLNcCayA9vc5z0n4ce5nnyrgf+WQolU37owMaBS41KiS8/sEYDkvH+w5JtlZSa9FVHQJchhoxNCRv008p39nIUUj3xHF2cDXQqL0OSl0kDe+oZY/a26VnrLvXPQG8gEvNC0F9PQ+DUwkT0WeDcvxn665/GH6QgnhL4k6PllbW82ayitSFswi1eIQhhPup/zpf9C2uie2qNEsaJezf+WWRrkIxUTYMM/cWphzwMiBTES1qWFGlLQATxPBg1175fX11WH44HLAH2RzgH30mHP4E7AFBWcflInVjBLf0rRBwaaYFfRN8FMf9w1Uavs0T6mlMOUxC/ZPSirq8qxoilj70Bgfz/zqmA/g5z0MugMFDHDTCBLCuEqyFPjeoK5RIAHYbQK169ZMeqUVGxBiAnu6uv7AHUCcHIqCPcyrflNTTs6s/9v6DqC0RRW7UIscw0qzCF7BLNhw7a4grXHSJjrC80wTdmlwloTlAj+F58/EoBeTjG0KoYmKd/iXvFNoM8D2C2q3Z2v0ME8jXnuWGRXmzat6TbG6v2fkeKmxFwfeWVjH+Fq7YEU5+rWwn8ud8pPVn3hKRbdA="
before_install:
    - yes | sdkmanager "platforms;android-28"
